### PR TITLE
lf_lifo: fix UB on pointer arithmetic with NULL

### LINKED ISSUE #104: runtime error: applying non-zero offset 1 to null pointer
clang with -fsanitize=undefined produces the error "include/small/lf_lifo.h:86:59: runtime error: applying non-zero offset 1 to null pointer" when running our test suite. 
The error is indirectly triggered by calling slab_cache_destroy. I can try to provide a simplified test case if needed.
Source of lf_lifo.h:86 is 

    void *newhead = (char *) elem + aba_value((char *) tail + 1);

### PR DESCRIPTION
**Pull request by nshy**
ASAN report:

```
tarantool/src/lib/small/include/small/lf_lifo.h:86:59: runtime error: applying non-zero offset 1 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/shiny/dev/tarantool/src/lib/small/include/small/lf_lifo.h:86:59
```

Let's explicitly handle NULL pointer case. Also add test for implementation defined behaviour on integer to pointer conversion and back. We rely on this behaviour for ABA counter for NULL pointer.

Note that currently we globally suppress some UB issues so we do not check the fix in CI yet. Manual check is done.
Before patch, without suppressions test is failed as described above and passed after patch.

Removed suppressions:
```diff
diff --git a/cmake/compiler.cmake b/cmake/compiler.cmake
index d6db669f05..e057f0dea5 100644
--- a/cmake/compiler.cmake
+++ b/cmake/compiler.cmake
@@ -236,18 +236,14 @@ macro(enable_tnt_compile_flags)
         string(JOIN "," UBSAN_IGNORE_OPTIONS
             # Gives compilation warnings when -O0 is used, which is always,
             # because some tests build with -O0.
-            object-size
             # See https://github.com/tarantool/tarantool/issues/10742.
-            pointer-overflow
             # NULL checking is disabled, because this is not a UB and raises
             # lots of false-positive fails such as typeof(*obj) with
             # obj == NULL, or memcpy() with NULL argument and 0 size.
             # "UBSan: check null is globally suppressed",
             # https://github.com/tarantool/tarantool/issues/10741
-            null
             # "UBSan: check nonnull-attribute is globally suppressed",
             # https://github.com/tarantool/tarantool/issues/10740
-            nonnull-attribute
         )
         # GCC has no "function" UB check. See details here:
```

Closes #104

Module bump in Tarantool PR is https://github.com/tarantool/tarantool/pull/11296.

### CODE REVIEW

File: include/small/lf_lifo.h [hunk 1]
```diff
@@ -79,11 +82,8 @@ lf_lifo_push(struct lf_lifo *head, void *elem)
 	do {
 		void *tail = head->next;
 		lf_lifo(elem)->next = tail;
-		/*
-		 * Sic: add 1 thus let ABA value overflow, *then*
-		 * coerce to unsigned short
-		 */
-		void *newhead = (char *) elem + aba_value((char *) tail + 1);
+		void *newhead = (char *)elem +
+				(unsigned short)(aba_value(tail) + 1);
```
Comment (sergepetrenko) [inline include/small/lf_lifo.h:86]: If I'm not mistaken it's only guaranteed that unsigned short is not less than 16 bits wide. But it might be more in some crazy case? In this case you'd shift newhead 1 step further than needed.

What I'm trying to say is wouldn't it be better to fix it like this?
```diff
diff --git a/include/small/lf_lifo.h b/include/small/lf_lifo.h
index 8181fef..f3f6973 100644
--- a/include/small/lf_lifo.h
+++ b/include/small/lf_lifo.h
@@ -83,7 +83,7 @@ lf_lifo_push(struct lf_lifo *head, void *elem)
                 * Sic: add 1 thus let ABA value overflow, *then*
                 * coerce to unsigned short
                 */
-               void *newhead = (char *) elem + aba_value((char *) tail + 1);
+               void *newhead = (char *) elem + aba_value((intptr_t) tail + 1);
                if (pm_atomic_compare_exchange_weak(&head->next, &tail, newhead))
                        return head;
        } while (true);
```

Comment (sergepetrenko) [reply include/small/lf_lifo.h:86]: ... or like this:
```
aba_value(aba_value(tail) + 1)
```

Comment (nshy) [reply include/small/lf_lifo.h:86]: They both require more casting:

```c
void *newhead = (char *) elem + aba_value((void *)((intptr_t) tail + 1));
```
and
```c
aba_value((void *)(aba_value(tail) + 1))
```

May use explicit mask?
```c
                void *newhead = (char *) elem +
                                ((aba_value(tail) + 1) & SMALL_LIFO_ALIGNMENT);
```

Comment (sergepetrenko) [reply include/small/lf_lifo.h:86]: > They both require more casting:
> 
> ```c
> void *newhead = (char *) elem + aba_value((void *)((intptr_t) tail + 1));
> ```

Yes but you have a similar cast in the other place on line 112:
```c
newhead = (void *)(intptr_t)aba_value(tail)
```
I don't think it looks too bad. IMO it looks better this way rather than with an explicit mask (previously the mask wasn't used anywhere except `aba_value` and `lf_lifo`.

Feel free to choose any of the discussed variants.

Comment (nshy) [reply include/small/lf_lifo.h:86]: I'd like to use explicit mask as otherwise we use `aba_value` in a complex ways. Is is intended to extract value from pointer so we have to cast back and forth to be able to use it. We can introduce a function to increment aba value but it is used in a single place and looks like it is better to open code it in `lf_lifo_push`.

I also changed return type of `aba_value()` to avoid extra casting in line 112.

Comment (sergepetrenko) [reply include/small/lf_lifo.h]: Ok, thanks for the fix!

**Review by sergepetrenko — APPROVED** [review]
